jam_terbang/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-item', add_item, name='add_item'), 
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),

    path('item/<int:id>/increment', increment_item, name='increment_item'),
    path('item/<int:id>/decrement', decrement_item, name='decrement_item'),
    
    path('user/items/', get_user_items, name='get_user_items'),
    path('create-ajax', add_user_item, name='add_user_item'),
    path('delete-ajax', delete_user_item, name='delete_user_item'),
    path('increment-ajax', increment_user_item, name='increment_user_item'),
    path('decrement-ajax', decrement_user_item, name='decrement_user_item'),

    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('get-flutter/<int:id>/', get_product_flutter, name='get_product_flutter'),
]  

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model) : 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.PositiveIntegerField()
    description = models.TextField()
    
    def __str__(self) : 
        return self.name + f"<{self.id}>"

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponseNotFound
from main.forms import ItemForm
from main.models import Item
from django.urls import reverse

from django.http import HttpResponse
from django.core import serializers

from django.db.models import Sum

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test

import datetime
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt
import json

@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    last_item_id = -1
    if (items.last()) : 
        items.last().id
    # get the sum of a column
    # from https://stackoverflow.com/questions/8616343/django-calculate-the-sum-of-the-column-values-through-query
    sum = items.aggregate(Sum('amount'))['amount__sum']
    if sum is None : 
        sum = 0

    context = {
        'nama': request.user.username,
        'kelas': 'PBP A',
        'items' : items,
        'most-items': items.order_by('amount').values(),
        'sum': sum,
        'last_login': request.COOKIES.get('last_login'),
        'last_item_id': last_item_id
    }

    return render(request, "main.html", context)

def add_item(request) :
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user 
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "add_item.html", context)

def show_html(request): 
    items = Item.objects.all()
    context = {
        'items' : items,
    }
    return render(request, "show_html.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request) :
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        
        print("inside request.POST: ")
        print(request.POST)
        print("inside form: ")
        print(form)

        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@login_required
def increment_item(request, id) : 
    data = Item.objects.get(pk=id)
    data.amount+=1
    data.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@login_required
def decrement_item(request, id) : 
    data = Item.objects.get(pk=id)
    data.amount-=1
    data.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def id_check(user, requested_id) : 
    requested_user = User.objects.get(pk=requested_id)
    return user.username == requested_user.username

@login_required
def get_user_items (request) : 
    items = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', items))

@csrf_exempt
@login_required 
def add_user_item(request) : 
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse("CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
@login_required
def increment_user_item (request) : # using ajax 
    if request.method == 'PATCH':
        data = json.loads(request.body.decode('utf-8'))
        item = Item.objects.get(pk=data.get("id"))
        item.amount+=1
        item.save()
        return HttpResponse("OK", status=200)

    return HttpResponseNotFound()

@csrf_exempt
@login_required
def decrement_user_item (request) : 
    if request.method == 'PATCH':
        data = json.loads(request.body.decode('utf-8'))
        item = Item.objects.get(pk=data.get("id"))
        item.amount-=1

        if (item.amount >= 0) :
            item.save()
            return HttpResponse("OK", status=200)
        else : 
            return HttpResponse("BAD REQUEST", status=400)

    return HttpResponseNotFound()

@csrf_exempt
@login_required
def delete_user_item (request) : 
    if request.method == 'DELETE':
        data = json.loads(request.body.decode('utf-8'))
        item = Item.objects.get(pk=data.get("id"))
        item.delete()
        return HttpResponse("OK", status=200)

    return HttpResponseNotFound() 

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        print(request.user)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

def get_product_flutter(request, id):
    data = Item.objects.filter(user=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

main/templates/add_item.html
{% extends 'base.html' %} 

{% block content %}
<h1 class="text-center">Add New Item</h1>

<form method="POST">
    {% csrf_token %}
    <table class="table form-group">
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input class="btn btn-primary" type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "container-fluid min-vh-100 login position-relative">
    <div class= "position-absolute top-50 start-50 translate-middle border rounded px-4 py-5">
            <h1 class="text-center">Login</h1>
        
            <form method="POST" action="" class="d-flex flex-column gap-3">
                {% csrf_token %}
                <table>
                    <tr class="form-group">
                        <td>Username: </td>
                        <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                    </tr>
                            
                    <tr class="form-group">
                        <td>Password: </td>
                        <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                    </tr>
                </table>
                <input class="btn btn-primary w-100" type="submit" value="Login">
            </form>
        
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     
                
            Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
    </div>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} 
{% block meta %}
<title>JamTerbang</title>
{% endblock meta %} 

{% block content %}
<div class="d-flex flex-column gap-3">
    <div>
        <div>
            <h4>Nama:</h4>
            <p>{{ nama }}</p>
        </div>
        <div>
            <h4>Kelas:</h4>
            <p>{{ kelas }}</p>
        </div>
    </div>
    
    <h4>Here are your items:</h4>
    <!-- <div class="d-flex gap-3"> 
        {% for item in items %} 
            <div class="card p-3">
                <h2>
                    {{ item.name }}
                </h2>
                <div>
                    {{ item.amount }}
                </div>
                <div>
                    {{ item.description }}
                </div>
            </div>
        {% endfor %}
    </div> -->

    <div>
        <div class="d-flex gap-3 flex-column" id="item_cards"></div>
        <!-- <table class="table">
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Description</th>
            </tr>
            {% for item in items %}
            
            {% if item.id == last_item_id %} 
            <tr>
                <td style="color: red;">{{ item.name }} </td>
                <td style="color: red;" class="d-flex gap-2">
                    
                    <form action="{% url 'main:decrement_item' item.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-secondary">-</button>
                    </form>
                    <div>
                        {{ item.amount }}
                    </div>
                    <form action="{% url 'main:increment_item' item.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-secondary">+</button>
                    </form>
                    
                </td>                    
                <td style="color: red;">{{ item.description }}</td>
            </tr>
            {% else %}
            <tr >
                <td>{{ item.name }}</td>
                <td class="d-flex gap-2">
                    
                    <form action="{% url 'main:decrement_item' item.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-secondary">-</button>
                    </form>
                    <div>
                        {{ item.amount }}
                    </div>
                    <form action="{% url 'main:increment_item' item.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-secondary">+</button>
                    </form>
                    
                </td>
            </td>
            <td>{{ item.description }}</td>
        </tr>
        {% endif %}
        {% endfor %} 
    </table> -->
    <div class="container-fluid">
        <div class="row py-3">
            <div class="col-md-12 text-center"> Kamu menyimpan {{ sum }} item</div>
        </div> 
        <div class="row">
                <a href="{% url 'main:add_item' %}" class="col-md-6"><button class="btn btn-primary w-100">Add New Item</button></a>
                <button type="button" class="btn btn-primary col-md-6" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
            </div>
        </div>
    </div>

    
    <div class="container-fluid">
        <p>Sesi terakhir login: {{ last_login }}</p>
        <a href="{% url 'main:logout' %}">
            <button class="btn btn-primary">
                Logout
            </button>
        </a>
    </div>

</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getItems() {
        return fetch("{% url 'main:get_user_items' %}")
            .then((res) => res.json())
    }

    function deleteItem(id) {
        alert("Deleting item with id " + id)
        fetch("{% url 'main:delete_user_item' %}", {
            method: "DELETE",
            body: JSON.stringify({
                id : id
            })
        }).then(refreshItems)
    }

    function addItem() {
        fetch("{% url 'main:add_user_item' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItems)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addItem

    function incrementItem(id) {
        fetch("{% url 'main:increment_user_item'%}", {
            method: "PATCH",
            body: JSON.stringify({
                id : id
            })
        }).then(refreshItems)
    }

    function decrementItem(id) {
        fetch("{% url 'main:decrement_user_item'%}", {
            method: "PATCH",
            body: JSON.stringify({
                id : id
            })
        }).then(refreshItems)
    }

    async function refreshItems() {
        const items = await getItems(); 
        document.getElementById("item_cards").innerHTML = "";
        let htmlString = ""
        for (let i = 0; i<items.length; i++) {
            let id = items[i].pk; 
            let item = items[i].fields;

            let cardClass="card p-3"; 
            let buttonClass = "btn btn-sm btn-secondary";
            if (i+1 == items.length) {
                cardClass += " bg-secondary text-light";
                buttonClass += " bg-light text-dark";
            }
            
            htmlString += `\n
            <div class="${cardClass}" id="item-${id}">
                <h2>
                    ${ item.name } 
                </h2>
                <div>
                    <button class="${buttonClass}" onclick="incrementItem(${id})">+</button> 
                    ${ item.amount } 
                    <button ${item.amount > 0 ? "" : "disabled"} class="${buttonClass}" onclick="decrementItem(${id})">-</button> 
                </div>
                <div class= "rounded my-1 py-2">
                    ${ item.description }
                </div>
                <button class="btn btn-sm btn-danger absolute" onclick="deleteItem(${id})">X</button>
            </div>
            ` 
        }

        document.getElementById("item_cards").innerHTML = htmlString
    }

    refreshItems()
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1 class="text-center">Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table class="table">  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="btn btn-primary" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

main/templates/show_html.html
<table>
    <tr>
        <th>Name</th>
        <th>Amount</th>
        <th>Description</th>
    </tr>
    {% for item in items %}
    <tr>
        <td>{{ item.name }}</td>
        <td>{{ item.amount }}</td>
        <td>{{ item.description }}</td>
    </tr>
    {% endfor %} 
</table>